# -------------------------------------------------------------------------------
# Name:        configure.py
# Purpose:     The file is automatically generated by tools.
# Author:      CD QA Team
# Created:     2020-09-28 17:02
# -------------------------------------------------------------------------------
# Android屏幕高
android_resolution_height = 720
# Android截图存放路径
android_screen_shot_path = r"/tsp"
# Konstanter串口波特率
konstanter_serial_baud_rate = 115200
# Android屏幕宽
android_resolution_width = 1920
# SOC串口波特率
soc_serial_baud_rate = 115200
# MCU串口波特率
mcu_serial_baud_rate = 115200
# IT6831串口号
it6831_serial_port = r"COM26"
# 安卓设备号
android_device_id = r"1234567"
# 空调屏(QNX)串口波特率
air_condition_baud_rate = 115200
# SOC串口号
soc_serial_port = r"COM26"
# 测试类型
test_case_type = r"仪表"
# 安卓的启动应用的activity
android_app_activity = r".SettingsActivity"
# QNX屏幕高
qnx_resolution_height = 720
# 最大支持的继电器通道
max_relay_channel = 8
# IT6831串口波特率
it6831_serial_baud_rate = 115200
# 最大QNX显示屏的个数
max_qnx_display = 2
# 空调屏(QNX)串口配置
air_condition_port = r"COM26"
# DBC文件名称
dbc_file = r"D:\Workspace\github\code\file\HiFire_B31CP_Info_HU_CAN_V2.0.dbc"
# 安卓系统版本号
android_version = r"8.1.0"
# 安卓的启动应用的package
android_app_package = r"com.chinatsp.settings"
# 电源电压支持最小电压
voltage_min = 10
# QNX屏幕宽
qnx_resolution_width = 1920
# QNX截图存放路径
qnx_screen_shot_path = r"/tsp"
# Android自动化测试方式
android_automation_type = r"appium"
# DBC解析后生成的文件名称
dbc_json = r"HiFire_B31CP_Info_HU_CAN_V2.0.json"
# 最大安卓显示屏的个数
max_android_display = 2
# Konstanter串口号
konstanter_serial_port = r"COM26"
# MCU串口号
mcu_serial_port = r"COM26"
# 电源电压支持最大电压
voltage_max = 20
