# -------------------------------------------------------------------------------
# Name:        test_adas_click.py
# Purpose:     The file is automatically generated by tools.
# Author:      CD QA Team
# Created:     2020-10-09 16:47
# -------------------------------------------------------------------------------
import allure
import pytest
from time import sleep
from automotive import *
from src.code.context import Tester

tester = Tester()


########################################################################################################################
#                                                                                                                      #
#                                                    创建Suite                                                          #
#                                                                                                                      #
########################################################################################################################
@pytest.fixture(scope="class", autouse=True)
@allure.suite("创建ADAS_Click测试套件")
def suite():
    with allure.step("打开CAN盒子"):
        tester.open_device()
        tester.ign_on()
        sleep(10)
        tester.vehiclespeed_0km()
    yield suite
    with allure.step("关闭CAN盒子"):
        tester.close_device()


########################################################################################################################
#                                                                                                                      #
#                                                    创建Function                                                       #
#                                                                                                                      #
########################################################################################################################
@pytest.fixture(scope="function", autouse=True)
def function():
    with allure.step("无"):
        pass
    yield
    with allure.step("无"):
        pass


########################################################################################################################
#                                                                                                                      #
#                                                    创建测试用例                                                        #
#                                                                                                                      #
########################################################################################################################
@allure.feature("module")
@pytest.mark.usefixtures("suite")
class TestADAS_Click(object):

    @pytest.mark.usefixtures("function")
    @allure.title("自动泊车寻车开关开启")
    def test_adv_park_click(self):
        """
        Description:
            自动泊车寻车开关开启
        PreCondition:
            1.空调屏收到信号[0X250]ADV_1:ADV_ParkStatus=0x1
        Steps:
            1.点击自动泊车寻车开关按钮
        Expect Result:
            1.空调屏发送对应请求信号：
            [0X2E1]FCP_2:FCP_APAFunctionReq=0x2（ON）
        """
        # 前置条件
        with allure.step("前置条件"):
            tester.adv_park_standby()
        # 执行步骤
        with allure.step('操作步骤'):
            tester.can_service.clear_stack_data()
            tester.ops_adv_park_button()
        # 期望结果
        with allure.step('期望结果'):
            stack = tester.can_service.get_stack()
            result = tester.cancompare_adv_park_click(stack)
            if len(result) > 1:
                result, images, compare_type, dark, light = result
                if compare_type == CompareTypeEnum.LIGHT:
                    allure.attach.file(light, '原图(亮图)', allure.attachment_type.BMP)
                elif compare_type == CompareTypeEnum.DARK:
                    allure.attach.file(dark, '原图(暗图)', allure.attachment_type.BMP)
                elif compare_type == CompareTypeEnum.BLINK:
                    allure.attach.file(light, '原图(亮图)', allure.attachment_type.BMP)
                    allure.attach.file(dark, '原图(暗图)', allure.attachment_type.BMP)
                result_str = "成功" if result else "失败"
                for image in images:
                    image_name = image.split("\\")[-1]
                    allure.attach.file(image, f"{result_str}截图[{image_name}]", allure.attachment_type.BMP)
                assert result
            else:
                assert result

    @pytest.mark.usefixtures("function")
    @allure.title("自动泊车寻车开关开启1")
    def test_adv_park_click1(self):
        """
        Description:
            自动泊车寻车开关开启1
        PreCondition:
            1.空调屏收到ADV ParkStatus信号
            [0X250]ADV_1:ADV_ParkStatus = 0x2
        Steps:
            1.点击自动泊车寻车开关按钮
        Expect Result:
            1.空调屏发送对应请求信号：
            [0X2E1]FCP_2:FCP_APAFunctionReq=0x1（OFF）
        """
        # 前置条件
        with allure.step("前置条件"):
            tester.adv_searchingforpark_in()
        # 执行步骤
        with allure.step('操作步骤'):
            tester.can_service.clear_stack_data()
            tester.ops_adv_park_button()
        # 期望结果
        with allure.step('期望结果'):
            stack = tester.can_service.get_stack()
            result = tester.cancompare_adv_park_click1(stack)
            if len(result) > 1:
                result, images, compare_type, dark, light = result
                if compare_type == CompareTypeEnum.LIGHT:
                    allure.attach.file(light, '原图(亮图)', allure.attachment_type.BMP)
                elif compare_type == CompareTypeEnum.DARK:
                    allure.attach.file(dark, '原图(暗图)', allure.attachment_type.BMP)
                elif compare_type == CompareTypeEnum.BLINK:
                    allure.attach.file(light, '原图(亮图)', allure.attachment_type.BMP)
                    allure.attach.file(dark, '原图(暗图)', allure.attachment_type.BMP)
                result_str = "成功" if result else "失败"
                for image in images:
                    image_name = image.split("\\")[-1]
                    allure.attach.file(image, f"{result_str}截图[{image_name}]", allure.attachment_type.BMP)
                assert result
            else:
                assert result
