# -------------------------------------------------------------------------------
# Name:        test_bcm.py
# Purpose:     The file is automatically generated by tools.
# Author:      CD QA Team
# Created:     2020-10-09 21:39
# -------------------------------------------------------------------------------
import allure
import pytest
from time import sleep
from src.code.context import Tester, compare


tester = Tester()


########################################################################################################################
#                                                                                                                      #
#                                                    创建Suite                                                          #
#                                                                                                                      #
########################################################################################################################
@pytest.fixture(scope="class", autouse=True)
@allure.suite("创建BCM测试套件")
def suite():
    with allure.step("打开CAN盒子"):
        tester.open_device()
        tester.ign_on()
        sleep(10)
    yield suite
    with allure.step("关闭CAN盒子"):
        tester.close_device()


########################################################################################################################
#                                                                                                                      #
#                                                    创建Function                                                       #
#                                                                                                                      #
########################################################################################################################
@pytest.fixture(scope="function", autouse=True)
def function():
    with allure.step("设置车速为0km/h"):
        tester.vehiclespeed_0km()
        sleep(1)
    yield
    with allure.step("恢复默认CAN消息"):
        pass


########################################################################################################################
#                                                                                                                      #
#                                                    创建测试用例                                                        #
#                                                                                                                      #
########################################################################################################################
@allure.feature("module")
@pytest.mark.usefixtures("suite")
class TestBCM(object):

    @pytest.mark.usefixtures("function")
    @allure.title("后风窗强制除霜开关高亮")
    def test_rear_window_heating_status_action(self):
        """
        Description:
            后风窗强制除霜开关高亮
        PreCondition:
            1.后风窗强制除霜开关关闭
        Steps:
            1.空调屏收到后窗加热active信号
            [0x240]BCM2_1:RearWindowHeatingStatus=0x1
        Expect Result:
            1.空调屏后风窗强制除霜开关高亮
        """
        # 前置条件
        with allure.step("前置条件"):
            tester.rear_window_heating_status_off()
        # 执行步骤
        with allure.step('操作步骤'):
            tester.rear_window_heating_status_on()
            tester.screenshot_rear_window_heating_status()
        # 期望结果
        with allure.step('期望结果'):
            assert True

    @pytest.mark.usefixtures("function")
    @allure.title("后风窗强制除霜开关高亮")
    def test_rear_window_heating_status_compare(self):
        """
        Description:
            后风窗强制除霜开关高亮
        PreCondition:
            1.后风窗强制除霜开关关闭
        Steps:
            1.空调屏收到后窗加热active信号
            [0x240]BCM2_1:RearWindowHeatingStatus=0x1
        Expect Result:
            1.空调屏后风窗强制除霜开关高亮
        """
        # 前置条件
        with allure.step("前置条件"):
            pass
        # 执行步骤
        with allure.step('操作步骤'):
            pass
        # 期望结果
        with allure.step('期望结果'):
            result = tester.compare_rear_window_heating_status()
            compare(result)
