# -------------------------------------------------------------------------------
# Name:        configure.py
# Purpose:     The file is automatically generated by tools.
# Author:      CD QA Team
# Created:     2020-10-11 22:13
# -------------------------------------------------------------------------------
# MCU串口波特率
mcu_serial_baud_rate = None
# DBC文件名称
dbc_file = r"HiFire_B31CP_Info_HU_CAN_V2.0.dbc"
# 测试类型
test_case_type = r"智能座舱"
# 安卓设备号
android_device_id = r"1234567"
# DBC解析后生成的文件名称
dbc_json = r"HiFire_B31CP_Info_HU_CAN_V2.0.json"
# QNX屏幕宽
qnx_resolution_width = 1920
# Android自动化测试方式
android_automation_type = None
# 安卓的启动应用的package
android_app_package = None
# 安卓系统版本号
android_version = r"8.1.0"
# 密码
password = None
# 最大QNX显示屏的个数
max_qnx_display = 1
# 空调屏(QNX)串口配置
air_condition_port = None
# 电源电压支持最大电压
voltage_max = None
# SOC串口号
soc_serial_port = None
# Konstanter串口号
konstanter_serial_port = None
# QNX截图存放路径
qnx_screen_shot_path = r"/tsp"
# 最大安卓显示屏的个数
max_android_display = 1
# SOC串口波特率
soc_serial_baud_rate = None
# Android屏幕宽
android_resolution_width = 1920
# Konstanter串口波特率
konstanter_serial_baud_rate = None
# IT6831串口号
it6831_serial_port = None
# Android屏幕高
android_resolution_height = 720
# QNX屏幕高
qnx_resolution_height = 720
# 最大支持的继电器通道
max_relay_channel = None
# 电源电压支持最小电压
voltage_min = None
# MCU串口号
mcu_serial_port = None
# 安卓的启动应用的activity
android_app_activity = None
# IT6831串口波特率
it6831_serial_baud_rate = None
# Android截图存放路径
android_screen_shot_path = r"/tsp"
# 空调屏(QNX)串口波特率
air_condition_baud_rate = None
# 用户名
username = None
