# -------------------------------------------------------------------------------
# Name:        test_mainpage.py
# Purpose:     The file is automatically generated by tools.
# Author:      CD QA Team
# Created:     2020-10-14 17:04
# -------------------------------------------------------------------------------
import pytest
from time import sleep
from automotive import *
from src.codes.context import *


########################################################################################################################
#                                                                                                                      #
#                                                    创建Suite                                                          #
#                                           s                                                                           #
########################################################################################################################
@pytest.fixture(scope="class", autouse=True)
@allure.suite("创建mainpage测试套件")
def suite():
    with allure.step("打开设备"):
        open_device()
        sleep(10)
    yield suite
    with allure.step("关闭设备"):
        close_device()


########################################################################################################################
#                                                                                                                      #
#                                                    创建Function                                                       #
#                                                                                                                      #
########################################################################################################################
@pytest.fixture(scope="function", autouse=True)
def function():
    with allure.step("无"):
        pass
    yield
    with allure.step("无"):
        enter_main_page()


########################################################################################################################
#                                                                                                                      #
#                                                    创建测试用例                                                        #
#                                                                                                                      #
########################################################################################################################
@allure.feature("module")
@pytest.mark.usefixtures("suite")
class TestMainpage(object):

    @pytest.mark.usefixtures("function")
    @allure.title("进入车辆设置界面")
    def test_enter_car_setting_page(self):
        """
        Description:
            进入车辆设置界面
        PreCondition:
            进入主界面
        Steps:
            进入车辆设置界面
        Expect Result:
            形式数据存在
        """
        # 前置条件
        with allure.step("前置条件"):
            sleep(5)
            logger.info("enter_car_setting_page")
            enter_car_setting_page()
            sleep(5)
            logger.info("enter_main_page")
            enter_main_page()
        # 执行步骤
        with allure.step('操作步骤'):
            logger.info("enter_car_setting_page")
            enter_car_setting_page()
        # # 期望结果
        with allure.step('期望结果'):
            compare(driver_date_exist())
