# -------------------------------------------------------------------------------
# Name:        test_bcm_compare.py
# Purpose:     The file is automatically generated by tools.
# Author:      CD QA Team
# Created:     2020-10-11 09:59
# -------------------------------------------------------------------------------
import pytest
from time import sleep
from src.codes.context import *


########################################################################################################################
#                                                                                                                      #
#                                                    创建Suite                                                          #
#                                                                                                                      #
########################################################################################################################
@pytest.fixture(scope="class", autouse=True)
@allure.suite("创建BCM测试套件")
def suite():
    with allure.step("打开CAN盒子"):
        pass
    yield suite
    with allure.step("关闭CAN盒子"):
        pass


########################################################################################################################
#                                                                                                                      #
#                                                    创建Function                                                       #
#                                                                                                                      #
########################################################################################################################
@pytest.fixture(scope="function", autouse=True)
def function():
    with allure.step("设置车速为0km/h"):
        pass
    yield
    with allure.step("恢复默认CAN消息"):
        pass


########################################################################################################################
#                                                                                                                      #
#                                                    创建测试用例                                                        #
#                                                                                                                      #
########################################################################################################################
@allure.feature("module")
@pytest.mark.usefixtures("suite")
class TestBCM(object):

    @pytest.mark.usefixtures("function")
    @allure.title("后风窗强制除霜开关高亮")
    def test_rear_window_heating_status_compare(self):
        """
        Description:
            后风窗强制除霜开关高亮
        PreCondition:
            1.后风窗强制除霜开关关闭
        Steps:
            1.空调屏收到后窗加热active信号
            [0x240]BCM2_1:RearWindowHeatingStatus=0x1
        Expect Result:
            1.空调屏后风窗强制除霜开关高亮
        """
        # 前置条件
        with allure.step("前置条件"):
            pass
        # 执行步骤
        with allure.step('操作步骤'):
            pass
        # 期望结果
        with allure.step('期望结果'):
            compare(compare_rear_window_heating_status())
